language: java
os: osx
osx_image: xcode9.3
sudo: required

before_install:
  # Install Java
  - brew update
  # Create a Homebrew Cask Caches folder
  # (See https://github.com/caskroom/homebrew-cask/issues/46403)
  - mkdir ~/Library/Caches/Homebrew/Cask
  - brew cask upgrade java
  # Install generate-app-icons
  - git clone https://github.com/saagarjha/GenerateAppIcons.git
  - xcodebuild -project GenerateAppIcons/GenerateAppIcons.xcodeproj/ -scheme GenerateAppIcons CODE_SIGNING_ALLOWED=NO

script:
  - ./CreateMarsApp.sh
